import type { Metadata } from "next";

import { Poppins } from "next/font/google";

import "./globals.css";

import { cn } from "@/lib/utils";

export const fontSans = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "InControl",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(fontSans.className)}>{children}</body>
    </html>
  );
}
